//
// ActionKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Describe of action kind */
public enum ActionKind: String, Codable, CaseIterable {
    case next = "Next"
    case back = "Back"
    case finish = "Finish"
    case dummy = "Dummy"
}
