//
// Action.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Parameters for action */
public struct Action: Codable, JSONEncodable, Hashable {

    /** List of conditioned actions */
    public var edges: [ConditionedAction]
    public var kind: ActionKind

    public init(edges: [ConditionedAction], kind: ActionKind) {
        self.edges = edges
        self.kind = kind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case edges
        case kind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(edges, forKey: .edges)
        try container.encode(kind, forKey: .kind)
    }
}

