//
// AssetUrl.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Asset from storage */
public struct AssetUrl: Codable, JSONEncodable, Hashable {

    public var origin: String
    public var thumb: String
    public var small: String
    public var medium: String
    public var normal: String

    public init(origin: String, thumb: String, small: String, medium: String, normal: String) {
        self.origin = origin
        self.thumb = thumb
        self.small = small
        self.medium = medium
        self.normal = normal
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case origin
        case thumb
        case small
        case medium
        case normal
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(origin, forKey: .origin)
        try container.encode(thumb, forKey: .thumb)
        try container.encode(small, forKey: .small)
        try container.encode(medium, forKey: .medium)
        try container.encode(normal, forKey: .normal)
    }
}

