//
// Asset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Asset */
public struct Asset: Codable, JSONEncodable, Hashable {

    public var assetUrl: AssetUrl?
    /** Asset name */
    public var assetName: String?

    public init(assetUrl: AssetUrl? = nil, assetName: String? = nil) {
        self.assetUrl = assetUrl
        self.assetName = assetName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case assetUrl
        case assetName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(assetUrl, forKey: .assetUrl)
        try container.encodeIfPresent(assetName, forKey: .assetName)
    }
}

