//
// BackgroundStyleKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Background style kind */
public enum BackgroundStyleKind: String, Codable, CaseIterable {
    case image = "image"
    case video = "video"
    case color = "color"
}
