//
// BackgroundStyleColor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Background color for screen */
public struct BackgroundStyleColor: Codable, JSONEncodable, Hashable {

    public var color: String

    public init(color: String) {
        self.color = color
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case color
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(color, forKey: .color)
    }
}

