//
// BackgroundStyle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Background styles configuration */
public struct BackgroundStyle: Codable, JSONEncodable, Hashable {

    public var kind: BackgroundStyleKind
    public var styles: BackgroundStyleStyles

    public init(kind: BackgroundStyleKind, styles: BackgroundStyleStyles) {
        self.kind = kind
        self.styles = styles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case styles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(styles, forKey: .styles)
    }
}

