//
// BadgeBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BadgeBlock: Codable, JSONEncodable, Hashable {

    public var textAlign: LabelPosition?
    public var fontFamily: FontFamily?
    /** Height of line */
    public var lineHeight: Double?
    /** Font size */
    public var fontSize: Double?
    /** Font weight */
    public var fontWeight: Double?
    /** Color for text */
    public var color: String?
    /** Background color for text block */
    public var backgroundColor: String?
    /** Padding left for container */
    public var paddingLeft: Double?
    /** Padding right for container */
    public var paddingRight: Double?
    /** Padding top for container */
    public var paddingTop: Double?
    /** Padding bottom for container */
    public var paddingBottom: Double?
    public var position: BadgePosition?
    /** Radius of border */
    public var borderRadius: Double?
    /** Width of border */
    public var borderWidth: Double?

    public init(textAlign: LabelPosition? = nil, fontFamily: FontFamily? = nil, lineHeight: Double? = nil, fontSize: Double? = nil, fontWeight: Double? = nil, color: String? = nil, backgroundColor: String? = nil, paddingLeft: Double? = nil, paddingRight: Double? = nil, paddingTop: Double? = nil, paddingBottom: Double? = nil, position: BadgePosition? = nil, borderRadius: Double? = nil, borderWidth: Double? = nil) {
        self.textAlign = textAlign
        self.fontFamily = fontFamily
        self.lineHeight = lineHeight
        self.fontSize = fontSize
        self.fontWeight = fontWeight
        self.color = color
        self.backgroundColor = backgroundColor
        self.paddingLeft = paddingLeft
        self.paddingRight = paddingRight
        self.paddingTop = paddingTop
        self.paddingBottom = paddingBottom
        self.position = position
        self.borderRadius = borderRadius
        self.borderWidth = borderWidth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case textAlign
        case fontFamily
        case lineHeight
        case fontSize
        case fontWeight
        case color
        case backgroundColor
        case paddingLeft
        case paddingRight
        case paddingTop
        case paddingBottom
        case position
        case borderRadius
        case borderWidth
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(textAlign, forKey: .textAlign)
        try container.encodeIfPresent(fontFamily, forKey: .fontFamily)
        try container.encodeIfPresent(lineHeight, forKey: .lineHeight)
        try container.encodeIfPresent(fontSize, forKey: .fontSize)
        try container.encodeIfPresent(fontWeight, forKey: .fontWeight)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(backgroundColor, forKey: .backgroundColor)
        try container.encodeIfPresent(paddingLeft, forKey: .paddingLeft)
        try container.encodeIfPresent(paddingRight, forKey: .paddingRight)
        try container.encodeIfPresent(paddingTop, forKey: .paddingTop)
        try container.encodeIfPresent(paddingBottom, forKey: .paddingBottom)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(borderRadius, forKey: .borderRadius)
        try container.encodeIfPresent(borderWidth, forKey: .borderWidth)
    }
}

