//
// BadgeBlockAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for badge block */
public struct BadgeBlockAllOf: Codable, JSONEncodable, Hashable {

    public var position: BadgePosition?
    /** Radius of border */
    public var borderRadius: Double?
    /** Width of border */
    public var borderWidth: Double?
    /** Color of border */
    public var borderColor: String?

    public init(position: BadgePosition? = nil, borderRadius: Double? = nil, borderWidth: Double? = nil, borderColor: String? = nil) {
        self.position = position
        self.borderRadius = borderRadius
        self.borderWidth = borderWidth
        self.borderColor = borderColor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case position
        case borderRadius
        case borderWidth
        case borderColor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(borderRadius, forKey: .borderRadius)
        try container.encodeIfPresent(borderWidth, forKey: .borderWidth)
        try container.encodeIfPresent(borderColor, forKey: .borderColor)
    }
}

