//
// BadgePosition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Badge position */
public enum BadgePosition: String, Codable, CaseIterable {
    case leftstart = "leftStart"
    case leftend = "leftEnd"
    case leftcenter = "leftCenter"
    case rightstart = "rightStart"
    case rightend = "rightEnd"
    case rightcenter = "rightCenter"
    case topleft = "topLeft"
    case topright = "topRight"
    case topcenter = "topCenter"
    case bottomleft = "bottomLeft"
    case bottomright = "bottomRight"
    case bottomcenter = "bottomCenter"
}
