//
// BaseDividerBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for divider */
public struct BaseDividerBlock: Codable, JSONEncodable, Hashable {

    public var color: String?
    public var height: Double?

    public init(color: String? = nil, height: Double? = nil) {
        self.color = color
        self.height = height
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case color
        case height
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(height, forKey: .height)
    }
}

