//
// BaseNavLink.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Base navigation link parameters */
public struct BaseNavLink: Codable, JSONEncodable, Hashable {

    public var kind: NavLinkKind
    public var content: BaseNavLinkContent
    public var styles: NavLinkBlock
    /** The uri Link */
    public var uri: String

    public init(kind: NavLinkKind, content: BaseNavLinkContent, styles: NavLinkBlock, uri: String) {
        self.kind = kind
        self.content = content
        self.styles = styles
        self.uri = uri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case content
        case styles
        case uri
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(content, forKey: .content)
        try container.encode(styles, forKey: .styles)
        try container.encode(uri, forKey: .uri)
    }
}

