//
// BaseNavLinkContent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Base navigation link content */
public enum BaseNavLinkContent: Codable, JSONEncodable, Hashable {
    case typeBaseImage(BaseImage)
    case typeBaseText(BaseText)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeBaseImage(let value):
            try container.encode(value)
        case .typeBaseText(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(BaseImage.self) {
            self = .typeBaseImage(value)
        } else if let value = try? container.decode(BaseText.self) {
            self = .typeBaseText(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of BaseNavLinkContent"))
        }
    }
}

