//
// BaseImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Base image parameters */
public struct BaseImage: Codable, JSONEncodable, Hashable {

    /** Dictionary of localized Asset */
    public var l10n: [String: Asset]
    public var styles: ImageBlock

    public init(l10n: [String: Asset], styles: ImageBlock) {
        self.l10n = l10n
        self.styles = styles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case l10n
        case styles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(l10n, forKey: .l10n)
        try container.encode(styles, forKey: .styles)
    }
}

