//
// BaseBadgeAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Base badge parameters */
public struct BaseBadgeAllOf: Codable, JSONEncodable, Hashable {

    public var styles: BadgeBlock

    public init(styles: BadgeBlock) {
        self.styles = styles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case styles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(styles, forKey: .styles)
    }
}

