//
// BaseDividerKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Kind of divider */
public enum BaseDividerKind: String, Codable, CaseIterable {
    case _default = "Default"
    case baseDividerKind1 = "BaseDividerKind1"
    case baseDividerKind2 = "BaseDividerKind2"
    case baseDividerKind3 = "BaseDividerKind3"
    case baseDividerKind4 = "BaseDividerKind4"
    case baseDividerKind5 = "BaseDividerKind5"
}
