//
// BasicFooterKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Basic footer kind */
public enum BasicFooterKind: String, Codable, CaseIterable {
    case vertical = "Vertical"
    case horizontal = "Horizontal"
    case basicFooterKind1 = "BasicFooterKind1"
    case basicFooterKind2 = "BasicFooterKind2"
    case basicFooterKind3 = "BasicFooterKind3"
    case basicFooterKind4 = "BasicFooterKind4"
    case basicFooterKind5 = "BasicFooterKind5"
}
