//
// BasicScreenBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Basic screen styles */
public struct BasicScreenBlock: Codable, JSONEncodable, Hashable {

    public var background: BackgroundStyle
    /** Padding left for body */
    public var paddingLeft: Double?
    /** Padding right for body */
    public var paddingRight: Double?
    /** Padding top for body */
    public var paddingTop: Double?
    /** Padding bottom for body */
    public var paddingBottom: Double?

    public init(background: BackgroundStyle, paddingLeft: Double? = nil, paddingRight: Double? = nil, paddingTop: Double? = nil, paddingBottom: Double? = nil) {
        self.background = background
        self.paddingLeft = paddingLeft
        self.paddingRight = paddingRight
        self.paddingTop = paddingTop
        self.paddingBottom = paddingBottom
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case background
        case paddingLeft
        case paddingRight
        case paddingTop
        case paddingBottom
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(background, forKey: .background)
        try container.encodeIfPresent(paddingLeft, forKey: .paddingLeft)
        try container.encodeIfPresent(paddingRight, forKey: .paddingRight)
        try container.encodeIfPresent(paddingTop, forKey: .paddingTop)
        try container.encodeIfPresent(paddingBottom, forKey: .paddingBottom)
    }
}

