//
// BasicPaywallBodyKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Basic paywall body kind */
public enum BasicPaywallBodyKind: String, Codable, CaseIterable {
    case mask = "mask"
    case gradient = "gradient"
}
