//
// BlurKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Blur kind */
public enum BlurKind: String, Codable, CaseIterable {
    case blurKind1 = "BlurKind1"
    case blurKind2 = "BlurKind2"
    case blurKind3 = "BlurKind3"
    case blurKind4 = "BlurKind4"
    case blurKind5 = "BlurKind5"
    case blurKind6 = "BlurKind6"
    case blurKind7 = "BlurKind7"
    case blurKind8 = "BlurKind8"
    case blurKind9 = "BlurKind9"
    case blurKind10 = "BlurKind10"
}
