//
// ButtonMovingAnimation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Button moving animation */
public enum ButtonMovingAnimation: String, Codable, CaseIterable {
    case buttonMovingAnimation1 = "ButtonMovingAnimation1"
    case buttonMovingAnimation2 = "ButtonMovingAnimation2"
    case buttonMovingAnimation3 = "ButtonMovingAnimation3"
    case buttonMovingAnimation4 = "ButtonMovingAnimation4"
    case buttonMovingAnimation5 = "ButtonMovingAnimation5"
    case buttonMovingAnimation6 = "ButtonMovingAnimation6"
    case buttonMovingAnimation7 = "ButtonMovingAnimation7"
    case buttonMovingAnimation8 = "ButtonMovingAnimation8"
    case buttonMovingAnimation9 = "ButtonMovingAnimation9"
    case buttonMovingAnimation10 = "ButtonMovingAnimation10"
}
