//
// ButtonKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Button kind */
public enum ButtonKind: String, Codable, CaseIterable {
    case text = "text"
    case image = "image"
}
