//
// ButtonVisibility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Button visibility */
public enum ButtonVisibility: String, Codable, CaseIterable {
    case _default = "default"
    case disableduntilvalueentered = "disabledUntilValueEntered"
    case hiddenuntilvalueentered = "hiddenUntilValueEntered"
}
