//
// CalendarBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for calendar */
public struct CalendarBlock: Codable, JSONEncodable, Hashable {

    /** Background of calendar */
    public var backgroundColor: String?
    /** Background of calendar header */
    public var headerBackgroundColor: String?
    public var headerLabel: LabelBlock
    public var headerWeekendLabel: LabelBlock
    public var todayLabel: LabelBlock
    public var monthLabel: LabelBlock
    public var currentMonthLabel: LabelBlock

    public init(backgroundColor: String? = nil, headerBackgroundColor: String? = nil, headerLabel: LabelBlock, headerWeekendLabel: LabelBlock, todayLabel: LabelBlock, monthLabel: LabelBlock, currentMonthLabel: LabelBlock) {
        self.backgroundColor = backgroundColor
        self.headerBackgroundColor = headerBackgroundColor
        self.headerLabel = headerLabel
        self.headerWeekendLabel = headerWeekendLabel
        self.todayLabel = todayLabel
        self.monthLabel = monthLabel
        self.currentMonthLabel = currentMonthLabel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case backgroundColor
        case headerBackgroundColor
        case headerLabel
        case headerWeekendLabel
        case todayLabel
        case monthLabel
        case currentMonthLabel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(backgroundColor, forKey: .backgroundColor)
        try container.encodeIfPresent(headerBackgroundColor, forKey: .headerBackgroundColor)
        try container.encode(headerLabel, forKey: .headerLabel)
        try container.encode(headerWeekendLabel, forKey: .headerWeekendLabel)
        try container.encode(todayLabel, forKey: .todayLabel)
        try container.encode(monthLabel, forKey: .monthLabel)
        try container.encode(currentMonthLabel, forKey: .currentMonthLabel)
    }
}

