//
// Calendar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Calendar */
public struct Calendar: Codable, JSONEncodable, Hashable {

    public var box: Box
    public var days: CalendarDays
    public var styles: CalendarBlock
    public var values: [String]

    public init(box: Box, days: CalendarDays, styles: CalendarBlock, values: [String]) {
        self.box = box
        self.days = days
        self.styles = styles
        self.values = values
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case box
        case days
        case styles
        case values
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(box, forKey: .box)
        try container.encode(days, forKey: .days)
        try container.encode(styles, forKey: .styles)
        try container.encode(values, forKey: .values)
    }
}

