//
// CalendarDays.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Calendar days config */
public struct CalendarDays: Codable, JSONEncodable, Hashable {

    public var past: CalendarDay
    public var today: CalendarDay
    public var future: CalendarDay
    public var weekend: CalendarDay

    public init(past: CalendarDay, today: CalendarDay, future: CalendarDay, weekend: CalendarDay) {
        self.past = past
        self.today = today
        self.future = future
        self.weekend = weekend
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case past
        case today
        case future
        case weekend
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(past, forKey: .past)
        try container.encode(today, forKey: .today)
        try container.encode(future, forKey: .future)
        try container.encode(weekend, forKey: .weekend)
    }
}

