//
// CalendarDay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Calendar day config */
public struct CalendarDay: Codable, JSONEncodable, Hashable {

    public var labelBlock: LabelBlock
    public var selectedLabelBlock: LabelBlock
    public var checkBox: BaseCheckBox

    public init(labelBlock: LabelBlock, selectedLabelBlock: LabelBlock, checkBox: BaseCheckBox) {
        self.labelBlock = labelBlock
        self.selectedLabelBlock = selectedLabelBlock
        self.checkBox = checkBox
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case labelBlock
        case selectedLabelBlock
        case checkBox
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(labelBlock, forKey: .labelBlock)
        try container.encode(selectedLabelBlock, forKey: .selectedLabelBlock)
        try container.encode(checkBox, forKey: .checkBox)
    }
}

