//
// CheckBoxKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Kind of checkbox */
public enum CheckBoxKind: String, Codable, CaseIterable {
    case square = "square"
    case circle = "circle"
}
