//
// CheckBoxBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for checkbox */
public struct CheckBoxBlock: Codable, JSONEncodable, Hashable {

    /** Color of checkbox */
    public var color: String?

    public init(color: String? = nil) {
        self.color = color
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case color
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(color, forKey: .color)
    }
}

