//
// CheckBox.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Checkbox parameters */
public struct CheckBox: Codable, JSONEncodable, Hashable {

    public var box: Box
    public var kind: CheckBoxKind
    /** Flag if checkbox checked */
    public var checked: Bool
    public var styles: CheckBoxBlock
    public var selectedBlock: SelectedCheckBoxBlock

    public init(box: Box, kind: CheckBoxKind, checked: Bool, styles: CheckBoxBlock, selectedBlock: SelectedCheckBoxBlock) {
        self.box = box
        self.kind = kind
        self.checked = checked
        self.styles = styles
        self.selectedBlock = selectedBlock
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case box
        case kind
        case checked
        case styles
        case selectedBlock
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(box, forKey: .box)
        try container.encode(kind, forKey: .kind)
        try container.encode(checked, forKey: .checked)
        try container.encode(styles, forKey: .styles)
        try container.encode(selectedBlock, forKey: .selectedBlock)
    }
}

