//
// CloseAppearance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Close button appearance kind */
public enum CloseAppearance: String, Codable, CaseIterable {
    case visible = "visible"
    case visibleaftertimer = "visibleAfterTimer"
}
