//
// CloseHorizontalAlignment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Close button horizontal alignment */
public enum CloseHorizontalAlignment: String, Codable, CaseIterable {
    case _left = "left"
    case _right = "right"
}
