//
// ConditionedAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Conditioned action */
public struct ConditionedAction: Codable, JSONEncodable, Hashable {

    /** List of conditions */
    public var rule: [Condition]
    /** Next screen id */
    public var nextScreenId: String
    public var transitionKind: ScreenTransitionKind

    public init(rule: [Condition], nextScreenId: String, transitionKind: ScreenTransitionKind) {
        self.rule = rule
        self.nextScreenId = nextScreenId
        self.transitionKind = transitionKind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rule
        case nextScreenId
        case transitionKind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rule, forKey: .rule)
        try container.encode(nextScreenId, forKey: .nextScreenId)
        try container.encode(transitionKind, forKey: .transitionKind)
    }
}

