//
// Condition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The condition */
public struct Condition: Codable, JSONEncodable, Hashable {

    /** Condition key */
    public var key: String
    public var _operator: Operator
    /** Comparison value */
    public var value: String

    public init(key: String, _operator: Operator, value: String) {
        self.key = key
        self._operator = _operator
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case _operator = "operator"
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(_operator, forKey: ._operator)
        try container.encode(value, forKey: .value)
    }
}

