//
// CurrencyFormatKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Currency format kind */
public enum CurrencyFormatKind: String, Codable, CaseIterable {
    case _none = "None"
    case decimal = "Decimal"
    case currency = "Currency"
    case percent = "Percent"
    case scientific = "Scientific"
    case spellOut = "SpellOut"
    case ordinal = "Ordinal"
    case currencyISOCode = "CurrencyISOCode"
    case currencyPlural = "CurrencyPlural"
    case currencyAccounting = "CurrencyAccounting"
}
