//
// CustomScreen.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomScreen: Codable, JSONEncodable, Hashable {

    public var navigationBar: NavigationBar
    public var footer: Footer
    public var styles: BasicScreenBlock
    public var permission: RequestPermission?
    public var timer: ScreenTimer?
    public var animationEnabled: Bool
    public var useLocalAssetsIfAvailable: Bool
    public var customScreenDescription: String
    /** Dictionary of output labels for custom screen */
    public var labels: [String: CustomScreenOutputLabel]
    /** Dictionary of input values from custom screen */
    public var values: [String: CustomScreenInputValue]
    public var callback: Callback

    public init(navigationBar: NavigationBar, footer: Footer, styles: BasicScreenBlock, permission: RequestPermission?, timer: ScreenTimer?, animationEnabled: Bool, useLocalAssetsIfAvailable: Bool, customScreenDescription: String, labels: [String: CustomScreenOutputLabel], values: [String: CustomScreenInputValue], callback: Callback) {
        self.navigationBar = navigationBar
        self.footer = footer
        self.styles = styles
        self.permission = permission
        self.timer = timer
        self.animationEnabled = animationEnabled
        self.useLocalAssetsIfAvailable = useLocalAssetsIfAvailable
        self.customScreenDescription = customScreenDescription
        self.labels = labels
        self.values = values
        self.callback = callback
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case navigationBar
        case footer
        case styles
        case permission
        case timer
        case animationEnabled
        case useLocalAssetsIfAvailable
        case customScreenDescription
        case labels
        case values
        case callback
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(navigationBar, forKey: .navigationBar)
        try container.encode(footer, forKey: .footer)
        try container.encode(styles, forKey: .styles)
        try container.encode(permission, forKey: .permission)
        try container.encode(timer, forKey: .timer)
        try container.encode(animationEnabled, forKey: .animationEnabled)
        try container.encode(useLocalAssetsIfAvailable, forKey: .useLocalAssetsIfAvailable)
        try container.encode(customScreenDescription, forKey: .customScreenDescription)
        try container.encode(labels, forKey: .labels)
        try container.encode(values, forKey: .values)
        try container.encode(callback, forKey: .callback)
    }
}

