//
// CustomScreenInputValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Custom screen input value, allows user to send data to onboarding flow */
public struct CustomScreenInputValue: Codable, JSONEncodable, Hashable {

    public var name: String
    public var type: ScreenInputType
    public var value: String

    public init(name: String, type: ScreenInputType, value: String) {
        self.name = name
        self.type = type
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
    }
}

