//
// CustomScreenAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Custom screen */
public struct CustomScreenAllOf: Codable, JSONEncodable, Hashable {

    public var customScreenDescription: String
    /** Dictionary of output labels for custom screen */
    public var labels: [String: CustomScreenOutputLabel]
    /** Dictionary of input values from custom screen */
    public var values: [String: CustomScreenInputValue]
    public var callback: Callback

    public init(customScreenDescription: String, labels: [String: CustomScreenOutputLabel], values: [String: CustomScreenInputValue], callback: Callback) {
        self.customScreenDescription = customScreenDescription
        self.labels = labels
        self.values = values
        self.callback = callback
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customScreenDescription
        case labels
        case values
        case callback
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customScreenDescription, forKey: .customScreenDescription)
        try container.encode(labels, forKey: .labels)
        try container.encode(values, forKey: .values)
        try container.encode(callback, forKey: .callback)
    }
}

