//
// DashesPageIndicatorBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for dashes page indicator block */
public struct DashesPageIndicatorBlock: Codable, JSONEncodable, Hashable {

    public var notFilledColor: String?
    public var filledColor: String?
    public var dashHeight: Double?
    public var dashesSpacing: Double?

    public init(notFilledColor: String? = nil, filledColor: String? = nil, dashHeight: Double? = nil, dashesSpacing: Double? = nil) {
        self.notFilledColor = notFilledColor
        self.filledColor = filledColor
        self.dashHeight = dashHeight
        self.dashesSpacing = dashesSpacing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notFilledColor
        case filledColor
        case dashHeight
        case dashesSpacing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notFilledColor, forKey: .notFilledColor)
        try container.encodeIfPresent(filledColor, forKey: .filledColor)
        try container.encodeIfPresent(dashHeight, forKey: .dashHeight)
        try container.encodeIfPresent(dashesSpacing, forKey: .dashesSpacing)
    }
}

