//
// FieldType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Possible field types */
public enum FieldType: String, Codable, CaseIterable {
    case string = "string"
    case int = "int"
    case double = "double"
    case date = "date"
}
