//
// FieldBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for field */
public struct FieldBlock: Codable, JSONEncodable, Hashable {

    /** Background color for field */
    public var backgroundColor: String?
    /** Border color for field */
    public var borderColor: String?

    public init(backgroundColor: String? = nil, borderColor: String? = nil) {
        self.backgroundColor = backgroundColor
        self.borderColor = borderColor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case backgroundColor
        case borderColor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(backgroundColor, forKey: .backgroundColor)
        try container.encodeIfPresent(borderColor, forKey: .borderColor)
    }
}

