//
// FontFamily.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Font family */
public enum FontFamily: String, Codable, CaseIterable {
    case sfPro = "SF Pro"
    case sfProrounded = "SF ProRounded"
    case sfMono = "SF Mono"
    case newYork = "New York"
}
