//
// FooterElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Enum of all footer elements */
public enum FooterElement: String, Codable, CaseIterable {
    case button1 = "Button1"
    case button2 = "Button2"
}
