//
// GradientKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Gradient kind */
public enum GradientKind: String, Codable, CaseIterable {
    case gradientKind1 = "GradientKind1"
    case gradientKind2 = "GradientKind2"
    case gradientKind3 = "GradientKind3"
    case gradientKind4 = "GradientKind4"
    case gradientKind5 = "GradientKind5"
    case gradientKind6 = "GradientKind6"
    case gradientKind7 = "GradientKind7"
    case gradientKind8 = "GradientKind8"
    case gradientKind9 = "GradientKind9"
    case gradientKind10 = "GradientKind10"
}
