//
// Image.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Image parameters */
public struct Image: Codable, JSONEncodable, Hashable {

    public var box: Box
    /** Dictionary of localized Asset */
    public var l10n: [String: Asset]
    public var styles: ImageBlock

    public init(box: Box, l10n: [String: Asset], styles: ImageBlock) {
        self.box = box
        self.l10n = l10n
        self.styles = styles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case box
        case l10n
        case styles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(box, forKey: .box)
        try container.encode(l10n, forKey: .l10n)
        try container.encode(styles, forKey: .styles)
    }
}

