//
// ImageKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Image kind */
public enum ImageKind: String, Codable, CaseIterable {
    case imageKind1 = "ImageKind1"
    case imageKind2 = "ImageKind2"
    case imageKind3 = "ImageKind3"
    case imageKind4 = "ImageKind4"
    case imageKind5 = "ImageKind5"
}
