//
// ImageScaleMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Image scale mode */
public enum ImageScaleMode: String, Codable, CaseIterable {
    case scaletofill = "scaleToFill"
    case scaleaspectfit = "scaleAspectFit"
    case scaleaspectfill = "scaleAspectFill"
    case center = "center"
    case top = "top"
    case bottom = "bottom"
    case _left = "left"
    case _right = "right"
}
