//
// ItemTypeSelection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Structure of full collection item type for selection list */
public struct ItemTypeSelection: Codable, JSONEncodable, Hashable {

    public var image: Image
    public var title: Text
    public var subtitle: Text
    public var checkBox: CheckBox
    public var action: Action
    public var box: Box
    public var weight: Double

    public init(image: Image, title: Text, subtitle: Text, checkBox: CheckBox, action: Action, box: Box, weight: Double) {
        self.image = image
        self.title = title
        self.subtitle = subtitle
        self.checkBox = checkBox
        self.action = action
        self.box = box
        self.weight = weight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
        case title
        case subtitle
        case checkBox
        case action
        case box
        case weight
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(image, forKey: .image)
        try container.encode(title, forKey: .title)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encode(checkBox, forKey: .checkBox)
        try container.encode(action, forKey: .action)
        try container.encode(box, forKey: .box)
        try container.encode(weight, forKey: .weight)
    }
}

