//
// LabelPosition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Position of label */
public enum LabelPosition: String, Codable, CaseIterable {
    case _left = "left"
    case _right = "right"
    case center = "center"
}
