//
// Language.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** language codes in ISO 639-1 and ISO 3166-1 standards */
public enum Language: String, Codable, CaseIterable {
    case ar = "ar"
    case ca = "ca"
    case zhHans = "zh-Hans"
    case zhHant = "zh-Hant"
    case hr = "hr"
    case cs = "cs"
    case da = "da"
    case nl = "nl"
    case enAu = "en-AU"
    case enCa = "en-CA"
    case enGb = "en-GB"
    case enUs = "en-US"
    case fi = "fi"
    case fr = "fr"
    case frCa = "fr-CA"
    case de = "de"
    case el = "el"
    case he = "he"
    case hi = "hi"
    case hu = "hu"
    case id = "id"
    case it = "it"
    case ja = "ja"
    case ko = "ko"
    case ms = "ms"
    case no = "no"
    case pl = "pl"
    case ptBr = "pt-BR"
    case ptPt = "pt-PT"
    case ro = "ro"
    case ru = "ru"
    case sk = "sk"
    case esMx = "es-MX"
    case esEs = "es-ES"
    case sv = "sv"
    case th = "th"
    case tr = "tr"
    case uk = "uk"
    case vi = "vi"
}
