//
// ListBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for list table */
public struct ListBlock: Codable, JSONEncodable, Hashable {

    public var verticalAlignment: VerticalAlignment?
    public var useMaxCellHeight: Bool?
    /** Background color for table */
    public var backgroundColor: String?
    /** Padding left for container */
    public var paddingLeft: Double?
    /** Padding right for container */
    public var paddingRight: Double?
    /** Padding top for container */
    public var paddingTop: Double?
    /** Padding bottom for container */
    public var paddingBottom: Double?
    /** Radius of border */
    public var borderRadius: Double?
    /** Color of border */
    public var borderColor: String?
    /** Width of border */
    public var borderWidth: Double?

    public init(verticalAlignment: VerticalAlignment? = nil, useMaxCellHeight: Bool? = nil, backgroundColor: String? = nil, paddingLeft: Double? = nil, paddingRight: Double? = nil, paddingTop: Double? = nil, paddingBottom: Double? = nil, borderRadius: Double? = nil, borderColor: String? = nil, borderWidth: Double? = nil) {
        self.verticalAlignment = verticalAlignment
        self.useMaxCellHeight = useMaxCellHeight
        self.backgroundColor = backgroundColor
        self.paddingLeft = paddingLeft
        self.paddingRight = paddingRight
        self.paddingTop = paddingTop
        self.paddingBottom = paddingBottom
        self.borderRadius = borderRadius
        self.borderColor = borderColor
        self.borderWidth = borderWidth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verticalAlignment
        case useMaxCellHeight
        case backgroundColor
        case paddingLeft
        case paddingRight
        case paddingTop
        case paddingBottom
        case borderRadius
        case borderColor
        case borderWidth
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(verticalAlignment, forKey: .verticalAlignment)
        try container.encodeIfPresent(useMaxCellHeight, forKey: .useMaxCellHeight)
        try container.encodeIfPresent(backgroundColor, forKey: .backgroundColor)
        try container.encodeIfPresent(paddingLeft, forKey: .paddingLeft)
        try container.encodeIfPresent(paddingRight, forKey: .paddingRight)
        try container.encodeIfPresent(paddingTop, forKey: .paddingTop)
        try container.encodeIfPresent(paddingBottom, forKey: .paddingBottom)
        try container.encodeIfPresent(borderRadius, forKey: .borderRadius)
        try container.encodeIfPresent(borderColor, forKey: .borderColor)
        try container.encodeIfPresent(borderWidth, forKey: .borderWidth)
    }
}

