//
// LoaderKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Loader kind */
public enum LoaderKind: String, Codable, CaseIterable {
    case circle = "Circle"
    case line = "Line"
    case loaderKind1 = "LoaderKind1"
    case loaderKind2 = "LoaderKind2"
    case loaderKind3 = "LoaderKind3"
    case loaderKind4 = "LoaderKind4"
    case loaderKind5 = "LoaderKind5"
}
