//
// LoaderKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Loader kind */
public enum LoaderKind: String, Codable, CaseIterable {
    case circle = "circle"
    case line = "line"
}
