//
// MediaContent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Media content */
public enum MediaContent: Codable, JSONEncodable, Hashable {
    case typeMediaImage(MediaImage)
    case typeMediaVideo(MediaVideo)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeMediaImage(let value):
            try container.encode(value)
        case .typeMediaVideo(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(MediaImage.self) {
            self = .typeMediaImage(value)
        } else if let value = try? container.decode(MediaVideo.self) {
            self = .typeMediaVideo(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of MediaContent"))
        }
    }
}

