//
// Media.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Media parameters */
public struct Media: Codable, JSONEncodable, Hashable {

    public var kind: MediaKind
    public var content: MediaContent
    public var styles: MediaBlock
    public var box: Box

    public init(kind: MediaKind, content: MediaContent, styles: MediaBlock, box: Box) {
        self.kind = kind
        self.content = content
        self.styles = styles
        self.box = box
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case content
        case styles
        case box
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(content, forKey: .content)
        try container.encode(styles, forKey: .styles)
        try container.encode(box, forKey: .box)
    }
}

