//
// MediaTopAlignment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Media top alignment */
public enum MediaTopAlignment: String, Codable, CaseIterable {
    case top = "top"
    case safearea = "safeArea"
    case navigationbar = "navigationBar"
}
