//
// MediaKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Media kind */
public enum MediaKind: String, Codable, CaseIterable {
    case image = "Image"
    case video = "Video"
}
