//
// MediaContent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Media content */
public enum MediaContent: Codable, JSONEncodable, Hashable {
    case typeBaseImage(BaseImage)
    case typeBaseVideo(BaseVideo)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeBaseImage(let value):
            try container.encode(value)
        case .typeBaseVideo(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(BaseImage.self) {
            self = .typeBaseImage(value)
        } else if let value = try? container.decode(BaseVideo.self) {
            self = .typeBaseVideo(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of MediaContent"))
        }
    }
}

