//
// NavigationBarElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Enum of all navigation bar elements */
public enum NavigationBarElement: String, Codable, CaseIterable {
    case back = "Back"
    case skip = "Skip"
    case pageIndicator = "PageIndicator"
}
