//
// NavigationBar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Navigation bar */
public enum NavigationBar: Codable, JSONEncodable, Hashable {
    case typeBasicNavigationBar(BasicNavigationBar)
    case typePaywallNavigationBar(PaywallNavigationBar)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeBasicNavigationBar(let value):
            try container.encode(value)
        case .typePaywallNavigationBar(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(BasicNavigationBar.self) {
            self = .typeBasicNavigationBar(value)
        } else if let value = try? container.decode(PaywallNavigationBar.self) {
            self = .typePaywallNavigationBar(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of NavigationBar"))
        }
    }
}

