//
// NavigationBar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Navigation bar */
public struct NavigationBar: Codable, JSONEncodable, Hashable {

    public var back: Button?
    public var skip: Button?
    public var pageIndicator: PageIndicator?

    public init(back: Button? = nil, skip: Button? = nil, pageIndicator: PageIndicator? = nil) {
        self.back = back
        self.skip = skip
        self.pageIndicator = pageIndicator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case back
        case skip
        case pageIndicator
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(back, forKey: .back)
        try container.encodeIfPresent(skip, forKey: .skip)
        try container.encodeIfPresent(pageIndicator, forKey: .pageIndicator)
    }
}

