//
// NavLinkKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Navigation link kind */
public enum NavLinkKind: String, Codable, CaseIterable {
    case text = "text"
    case image = "image"
}
