//
// PageIndicatorBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for page indicator */
public struct PageIndicatorBlock: Codable, JSONEncodable, Hashable {

    /** The line's color */
    public var color: String?
    /** The line's track color */
    public var trackColor: String?

    public init(color: String? = nil, trackColor: String? = nil) {
        self.color = color
        self.trackColor = trackColor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case color
        case trackColor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(trackColor, forKey: .trackColor)
    }
}

