//
// PageIndicatorKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Page indicator kind */
public enum PageIndicatorKind: String, Codable, CaseIterable {
    case line = "Line"
    case dashes = "Dashes"
    case dashesWithTitle = "DashesWithTitle"
    case dashesWithImage = "DashesWithImage"
    case dashesWithTitleImage = "DashesWithTitleImage"
    case pageIndicatorKind1 = "PageIndicatorKind1"
    case pageIndicatorKind2 = "PageIndicatorKind2"
    case pageIndicatorKind3 = "PageIndicatorKind3"
    case pageIndicatorKind4 = "PageIndicatorKind4"
    case pageIndicatorKind5 = "PageIndicatorKind5"
}
