//
// PaywallFooterBottomContainer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Paywall footer bottom container */
public struct PaywallFooterBottomContainer: Codable, JSONEncodable, Hashable {

    public var privacyPolicy: NavLink?
    public var restore: Text?
    public var termsOfUse: NavLink?
    public var styles: PaywallFooterBottomContainerBlock

    public init(privacyPolicy: NavLink? = nil, restore: Text? = nil, termsOfUse: NavLink? = nil, styles: PaywallFooterBottomContainerBlock) {
        self.privacyPolicy = privacyPolicy
        self.restore = restore
        self.termsOfUse = termsOfUse
        self.styles = styles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case privacyPolicy
        case restore
        case termsOfUse
        case styles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(privacyPolicy, forKey: .privacyPolicy)
        try container.encodeIfPresent(restore, forKey: .restore)
        try container.encodeIfPresent(termsOfUse, forKey: .termsOfUse)
        try container.encode(styles, forKey: .styles)
    }
}

