//
// PaywallFooterElementsOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Paywall footer elements order */
public enum PaywallFooterElementsOrder: String, Codable, CaseIterable {
    case purchaseFirst = "PurchaseFirst"
    case autoRenewLabelFirst = "AutoRenewLabelFirst"
    case paywallFooterOrder1 = "PaywallFooterOrder1"
    case paywallFooterOrder2 = "PaywallFooterOrder2"
    case paywallFooterOrder3 = "PaywallFooterOrder3"
    case paywallFooterOrder4 = "PaywallFooterOrder4"
    case paywallFooterOrder5 = "PaywallFooterOrder5"
}
