//
// PaywallImageVerticalPositionKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Paywall image vertical position kind */
public enum PaywallImageVerticalPositionKind: String, Codable, CaseIterable {
    case headerTitle = "HeaderTitle"
    case headerSubtitle = "HeaderSubtitle"
    case headerListTop = "HeaderListTop"
    case headerListBottom = "HeaderListBottom"
    case headerBottom = "HeaderBottom"
    case headerCenter = "HeaderCenter"
    case headerTop = "HeaderTop"
    case bodyBottom = "BodyBottom"
    case footerTop = "FooterTop"
    case paywallImageVerticalPositionKind1 = "PaywallImageVerticalPositionKind1"
    case paywallImageVerticalPositionKind2 = "PaywallImageVerticalPositionKind2"
    case paywallImageVerticalPositionKind3 = "PaywallImageVerticalPositionKind3"
    case paywallImageVerticalPositionKind4 = "PaywallImageVerticalPositionKind4"
    case paywallImageVerticalPositionKind5 = "PaywallImageVerticalPositionKind5"
}
