//
// PaywallNavigationBar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Paywall navigation bar */
public struct PaywallNavigationBar: Codable, JSONEncodable, Hashable {

    public var paywallNavigationBar: String
    public var close: Button?
    public var styles: PaywallNavigationBarBlock
    public var back: Button?
    public var skip: Button?
    public var pageIndicator: PageIndicator?

    public init(paywallNavigationBar: String, close: Button? = nil, styles: PaywallNavigationBarBlock, back: Button? = nil, skip: Button? = nil, pageIndicator: PageIndicator? = nil) {
        self.paywallNavigationBar = paywallNavigationBar
        self.close = close
        self.styles = styles
        self.back = back
        self.skip = skip
        self.pageIndicator = pageIndicator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paywallNavigationBar
        case close
        case styles
        case back
        case skip
        case pageIndicator
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(paywallNavigationBar, forKey: .paywallNavigationBar)
        try container.encodeIfPresent(close, forKey: .close)
        try container.encode(styles, forKey: .styles)
        try container.encodeIfPresent(back, forKey: .back)
        try container.encodeIfPresent(skip, forKey: .skip)
        try container.encodeIfPresent(pageIndicator, forKey: .pageIndicator)
    }
}

