//
// PaywallNavigationBarBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for paywall navigation bar */
public struct PaywallNavigationBarBlock: Codable, JSONEncodable, Hashable {

    public var closeHorizontalAlignment: CloseHorizontalAlignment?
    public var closeAppearance: CloseAppearance?
    /** Close button appearance visible after timer value in seconds */
    public var closeVisibleAfterTimerValue: Double?

    public init(closeHorizontalAlignment: CloseHorizontalAlignment? = nil, closeAppearance: CloseAppearance? = nil, closeVisibleAfterTimerValue: Double? = nil) {
        self.closeHorizontalAlignment = closeHorizontalAlignment
        self.closeAppearance = closeAppearance
        self.closeVisibleAfterTimerValue = closeVisibleAfterTimerValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case closeHorizontalAlignment
        case closeAppearance
        case closeVisibleAfterTimerValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(closeHorizontalAlignment, forKey: .closeHorizontalAlignment)
        try container.encodeIfPresent(closeAppearance, forKey: .closeAppearance)
        try container.encodeIfPresent(closeVisibleAfterTimerValue, forKey: .closeVisibleAfterTimerValue)
    }
}

