//
// PaywallFooterBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for paywall footer */
public struct PaywallFooterBlock: Codable, JSONEncodable, Hashable {

    public var elementsOrder: PaywallFooterElementsOrder?
    /** Background color for footer */
    public var backgroundColor: String?
    public var opacity: Double?

    public init(elementsOrder: PaywallFooterElementsOrder? = nil, backgroundColor: String? = nil, opacity: Double? = nil) {
        self.elementsOrder = elementsOrder
        self.backgroundColor = backgroundColor
        self.opacity = opacity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case elementsOrder
        case backgroundColor
        case opacity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(elementsOrder, forKey: .elementsOrder)
        try container.encodeIfPresent(backgroundColor, forKey: .backgroundColor)
        try container.encodeIfPresent(opacity, forKey: .opacity)
    }
}

