//
// PaywallFooter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Paywall footer */
public struct PaywallFooter: Codable, JSONEncodable, Hashable {

    public var paywallFooter: String
    public var purchase: Button?
    public var autoRenewLabel: Text?
    public var restore: Button?
    public var privacyPolicy: NavLink?
    public var termsOfUse: NavLink?
    public var styles: PaywallFooterBlock
    public var button1: Button?
    public var button2: Button?

    public init(paywallFooter: String, purchase: Button? = nil, autoRenewLabel: Text? = nil, restore: Button? = nil, privacyPolicy: NavLink? = nil, termsOfUse: NavLink? = nil, styles: PaywallFooterBlock, button1: Button? = nil, button2: Button? = nil) {
        self.paywallFooter = paywallFooter
        self.purchase = purchase
        self.autoRenewLabel = autoRenewLabel
        self.restore = restore
        self.privacyPolicy = privacyPolicy
        self.termsOfUse = termsOfUse
        self.styles = styles
        self.button1 = button1
        self.button2 = button2
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paywallFooter
        case purchase
        case autoRenewLabel
        case restore
        case privacyPolicy
        case termsOfUse
        case styles
        case button1
        case button2
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(paywallFooter, forKey: .paywallFooter)
        try container.encodeIfPresent(purchase, forKey: .purchase)
        try container.encodeIfPresent(autoRenewLabel, forKey: .autoRenewLabel)
        try container.encodeIfPresent(restore, forKey: .restore)
        try container.encodeIfPresent(privacyPolicy, forKey: .privacyPolicy)
        try container.encodeIfPresent(termsOfUse, forKey: .termsOfUse)
        try container.encode(styles, forKey: .styles)
        try container.encodeIfPresent(button1, forKey: .button1)
        try container.encodeIfPresent(button2, forKey: .button2)
    }
}

