//
// PaywallFooterElementsOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Paywall footer elements order */
public enum PaywallFooterElementsOrder: String, Codable, CaseIterable {
    case imagefirst = "imageFirst"
    case autorenewlabelfirst = "autoRenewLabelFirst"
}
