//
// PaywallBodyMaskKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Paywall body mask kind */
public enum PaywallBodyMaskKind: String, Codable, CaseIterable {
    case paywallBodyMaskKind1 = "PaywallBodyMaskKind1"
    case paywallBodyMaskKind2 = "PaywallBodyMaskKind2"
    case paywallBodyMaskKind3 = "PaywallBodyMaskKind3"
    case paywallBodyMaskKind4 = "PaywallBodyMaskKind4"
    case paywallBodyMaskKind5 = "PaywallBodyMaskKind5"
    case paywallBodyMaskKind6 = "PaywallBodyMaskKind6"
    case paywallBodyMaskKind7 = "PaywallBodyMaskKind7"
    case paywallBodyMaskKind8 = "PaywallBodyMaskKind8"
    case paywallBodyMaskKind9 = "PaywallBodyMaskKind9"
    case paywallBodyMaskKind10 = "PaywallBodyMaskKind10"
}
