//
// PickerWheel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Picker wheel */
public struct PickerWheel: Codable, JSONEncodable, Hashable {

    public var kind: PickerWheelKind
    public var options: PickerOptions
    /** Localized string */
    public var defaultValue: [String: String]

    public init(kind: PickerWheelKind, options: PickerOptions, defaultValue: [String: String]) {
        self.kind = kind
        self.options = options
        self.defaultValue = defaultValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case options
        case defaultValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(options, forKey: .options)
        try container.encode(defaultValue, forKey: .defaultValue)
    }
}

