//
// PickerWheelKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Picker wheel kind */
public enum PickerWheelKind: String, Codable, CaseIterable {
    case list = "list"
    case range = "range"
}
