//
// PickerOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Picker options */
public enum PickerOptions: Codable, JSONEncodable, Hashable {
    case typePickerListOptions(PickerListOptions)
    case typePickerRangeOptions(PickerRangeOptions)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typePickerListOptions(let value):
            try container.encode(value)
        case .typePickerRangeOptions(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(PickerListOptions.self) {
            self = .typePickerListOptions(value)
        } else if let value = try? container.decode(PickerRangeOptions.self) {
            self = .typePickerRangeOptions(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of PickerOptions"))
        }
    }
}

