//
// PickerListOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List picker select options */
public struct PickerListOptions: Codable, JSONEncodable, Hashable {

    /** Localized string */
    public var localizedOptions: [String: [String]]

    public init(localizedOptions: [String: [String]]) {
        self.localizedOptions = localizedOptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case localizedOptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(localizedOptions, forKey: .localizedOptions)
    }
}

