//
// ProgressBarKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Kind of progress bar */
public enum ProgressBarKind: String, Codable, CaseIterable {
    case circle = "circle"
    case line = "line"
}
