//
// ProgressBarKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Kind of progress bar */
public enum ProgressBarKind: String, Codable, CaseIterable {
    case circle = "circle"
    case line = "line"
    case multipleline = "multipleLine"
    case progressBarKind1 = "ProgressBarKind1"
    case progressBarKind2 = "ProgressBarKind2"
    case progressBarKind3 = "ProgressBarKind3"
    case progressBarKind4 = "ProgressBarKind4"
    case progressBarKind5 = "ProgressBarKind5"
}
