//
// ProgressBarItemContent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Progress bar item content */
public struct ProgressBarItemContent: Codable, JSONEncodable, Hashable {

    public var title: Text

    public init(title: Text) {
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
    }
}

