//
// ProgressBarItemBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for progress bar item */
public struct ProgressBarItemBlock: Codable, JSONEncodable, Hashable {

    /** Color for progress bar */
    public var color: String?
    /** Track color */
    public var trackColor: String?
    /** Fill color */
    public var fillColor: String?

    public init(color: String? = nil, trackColor: String? = nil, fillColor: String? = nil) {
        self.color = color
        self.trackColor = trackColor
        self.fillColor = fillColor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case color
        case trackColor
        case fillColor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(trackColor, forKey: .trackColor)
        try container.encodeIfPresent(fillColor, forKey: .fillColor)
    }
}

