//
// PurchaseFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Purchase flag */
public enum PurchaseFlag: String, Codable, CaseIterable {
    case shouldCloseAfterRestore = "ShouldCloseAfterRestore"
    case shouldCloseAfterSubscriptionError = "ShouldCloseAfterSubscriptionError"
}
