//
// RegularList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Regular list element */
public struct RegularList: Codable, JSONEncodable, Hashable {

    public var itemType: RegularListItemType
    /** Item rows */
    public var items: [ItemTypeRegular]
    public var styles: ListBlock
    public var box: Box

    public init(itemType: RegularListItemType, items: [ItemTypeRegular], styles: ListBlock, box: Box) {
        self.itemType = itemType
        self.items = items
        self.styles = styles
        self.box = box
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemType
        case items
        case styles
        case box
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(itemType, forKey: .itemType)
        try container.encode(items, forKey: .items)
        try container.encode(styles, forKey: .styles)
        try container.encode(box, forKey: .box)
    }
}

