//
// RegularListItemType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Combination of fields for regular list item */
public enum RegularListItemType: String, Codable, CaseIterable {
    case imageTitle = "ImageTitle"
    case titleImage = "TitleImage"
}
