//
// RegularListItemBlockElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Possible elements on regular list */
public enum RegularListItemBlockElement: String, Codable, CaseIterable {
    case image = "Image"
    case title = "Title"
}
