//
// RequestPermission.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request permissions object */
public struct RequestPermission: Codable, JSONEncodable, Hashable {

    public var type: ScreenPermissionType
    public var value: Bool
    public var action: Action

    public init(type: ScreenPermissionType, value: Bool, action: Action) {
        self.type = type
        self.value = value
        self.action = action
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
        case action
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
        try container.encode(action, forKey: .action)
    }
}

