//
// RestoreHorizontalAlignment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Restore text horizontal alignment */
public enum RestoreHorizontalAlignment: String, Codable, CaseIterable {
    case _left = "left"
    case _right = "right"
}
