//
// ScreenBasicPaywallBlock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScreenBasicPaywallBlock: Codable, JSONEncodable, Hashable {

    public var background: BackgroundStyle
    /** Padding left for body */
    public var paddingLeft: Double?
    /** Padding right for body */
    public var paddingRight: Double?
    /** Padding top for body */
    public var paddingTop: Double?
    /** Padding bottom for body */
    public var paddingBottom: Double?
    public var bodyColor: String?
    public var bodyOpacity: String?
    public var imageVerticalPosition: PaywallImageVerticalPositionKind?
    public var bodyBackgroundColor: String?
    public var bodyBackgroundOpacity: Double?
    public var bodyKind: BasicPaywallBodyKind?
    public var bodyStyle: BasicPaywallBodyStyle?
    public var blur: BlurKind?

    public init(background: BackgroundStyle, paddingLeft: Double? = nil, paddingRight: Double? = nil, paddingTop: Double? = nil, paddingBottom: Double? = nil, bodyColor: String? = nil, bodyOpacity: String? = nil, imageVerticalPosition: PaywallImageVerticalPositionKind? = nil, bodyBackgroundColor: String? = nil, bodyBackgroundOpacity: Double? = nil, bodyKind: BasicPaywallBodyKind? = nil, bodyStyle: BasicPaywallBodyStyle? = nil, blur: BlurKind? = nil) {
        self.background = background
        self.paddingLeft = paddingLeft
        self.paddingRight = paddingRight
        self.paddingTop = paddingTop
        self.paddingBottom = paddingBottom
        self.bodyColor = bodyColor
        self.bodyOpacity = bodyOpacity
        self.imageVerticalPosition = imageVerticalPosition
        self.bodyBackgroundColor = bodyBackgroundColor
        self.bodyBackgroundOpacity = bodyBackgroundOpacity
        self.bodyKind = bodyKind
        self.bodyStyle = bodyStyle
        self.blur = blur
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case background
        case paddingLeft
        case paddingRight
        case paddingTop
        case paddingBottom
        case bodyColor
        case bodyOpacity
        case imageVerticalPosition
        case bodyBackgroundColor
        case bodyBackgroundOpacity
        case bodyKind
        case bodyStyle
        case blur
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(background, forKey: .background)
        try container.encodeIfPresent(paddingLeft, forKey: .paddingLeft)
        try container.encodeIfPresent(paddingRight, forKey: .paddingRight)
        try container.encodeIfPresent(paddingTop, forKey: .paddingTop)
        try container.encodeIfPresent(paddingBottom, forKey: .paddingBottom)
        try container.encodeIfPresent(bodyColor, forKey: .bodyColor)
        try container.encodeIfPresent(bodyOpacity, forKey: .bodyOpacity)
        try container.encodeIfPresent(imageVerticalPosition, forKey: .imageVerticalPosition)
        try container.encodeIfPresent(bodyBackgroundColor, forKey: .bodyBackgroundColor)
        try container.encodeIfPresent(bodyBackgroundOpacity, forKey: .bodyBackgroundOpacity)
        try container.encodeIfPresent(bodyKind, forKey: .bodyKind)
        try container.encodeIfPresent(bodyStyle, forKey: .bodyStyle)
        try container.encodeIfPresent(blur, forKey: .blur)
    }
}

