//
// Screen.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Screen: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    /** Screen tags */
    public var tags: [String]
    public var screenType: ScreenType
    public var _struct: ScreenStruct
    public var position: PositionOnConfigurator

    public init(id: String, name: String, tags: [String], screenType: ScreenType, _struct: ScreenStruct, position: PositionOnConfigurator) {
        self.id = id
        self.name = name
        self.tags = tags
        self.screenType = screenType
        self._struct = _struct
        self.position = position
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case tags
        case screenType
        case _struct = "struct"
        case position
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(tags, forKey: .tags)
        try container.encode(screenType, forKey: .screenType)
        try container.encode(_struct, forKey: ._struct)
        try container.encode(position, forKey: .position)
    }
}

