//
// ScreenTableMultipleSelectionAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Screen table multiple selection - Title/Subtitle/Selection list */
public struct ScreenTableMultipleSelectionAllOf: Codable, JSONEncodable, Hashable {

    public var multipleSelectionDescription: String
    public var media: Media?
    public var title: Text
    public var subtitle: Text
    public var list: MultipleSelectionList

    public init(multipleSelectionDescription: String, media: Media? = nil, title: Text, subtitle: Text, list: MultipleSelectionList) {
        self.multipleSelectionDescription = multipleSelectionDescription
        self.media = media
        self.title = title
        self.subtitle = subtitle
        self.list = list
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case multipleSelectionDescription
        case media
        case title
        case subtitle
        case list
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(multipleSelectionDescription, forKey: .multipleSelectionDescription)
        try container.encodeIfPresent(media, forKey: .media)
        try container.encode(title, forKey: .title)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encode(list, forKey: .list)
    }
}

