//
// ScreensGraph.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The graph of screens for onboarding */
public struct ScreensGraph: Codable, JSONEncodable, Hashable {

    public var defaultLanguage: Language
    /** The list of languages */
    public var languages: [Language]
    /** First screen id */
    public var launchScreenId: String
    /** All screens nodes dictionary */
    public var screens: [String: Screen]
    /** Metadata dictionary */
    public var metadata: [String: String]

    public init(defaultLanguage: Language, languages: [Language], launchScreenId: String, screens: [String: Screen], metadata: [String: String]) {
        self.defaultLanguage = defaultLanguage
        self.languages = languages
        self.launchScreenId = launchScreenId
        self.screens = screens
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case defaultLanguage
        case languages
        case launchScreenId
        case screens
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(defaultLanguage, forKey: .defaultLanguage)
        try container.encode(languages, forKey: .languages)
        try container.encode(launchScreenId, forKey: .launchScreenId)
        try container.encode(screens, forKey: .screens)
        try container.encode(metadata, forKey: .metadata)
    }
}

