//
// ScreenTableSingleSelectionAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Screen table single selection - Title/Subtitle/Selection list */
public struct ScreenTableSingleSelectionAllOf: Codable, JSONEncodable, Hashable {

    public var singleSelectionDescription: String
    public var title: Text
    public var subtitle: Text
    public var list: SingleSelectionList

    public init(singleSelectionDescription: String, title: Text, subtitle: Text, list: SingleSelectionList) {
        self.singleSelectionDescription = singleSelectionDescription
        self.title = title
        self.subtitle = subtitle
        self.list = list
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case singleSelectionDescription
        case title
        case subtitle
        case list
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(singleSelectionDescription, forKey: .singleSelectionDescription)
        try container.encode(title, forKey: .title)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encode(list, forKey: .list)
    }
}

