//
// ScreenTimer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Timer to show the screen */
public struct ScreenTimer: Codable, JSONEncodable, Hashable {

    /** Duration to show some screen in seconds */
    public var duration: Int
    public var action: Action
    public var unit: TimerUnit?

    public init(duration: Int, action: Action, unit: TimerUnit? = nil) {
        self.duration = duration
        self.action = action
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case duration
        case action
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(duration, forKey: .duration)
        try container.encode(action, forKey: .action)
        try container.encodeIfPresent(unit, forKey: .unit)
    }
}

