//
// ScreenImageTitleSubtitles.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScreenImageTitleSubtitles: Codable, JSONEncodable, Hashable {

    public var navigationBar: NavigationBar
    public var footer: Footer
    public var styles: BasicScreenBlock
    public var permission: RequestPermission?
    public var timer: ScreenTimer?
    public var animationEnabled: Bool
    public var useLocalAssetsIfAvailable: Bool
    public var imageTitleSubtitlesDescription: String
    public var image: Image
    public var title: Text
    public var subtitle1: Text
    public var subtitle2: Text

    public init(navigationBar: NavigationBar, footer: Footer, styles: BasicScreenBlock, permission: RequestPermission?, timer: ScreenTimer?, animationEnabled: Bool, useLocalAssetsIfAvailable: Bool, imageTitleSubtitlesDescription: String, image: Image, title: Text, subtitle1: Text, subtitle2: Text) {
        self.navigationBar = navigationBar
        self.footer = footer
        self.styles = styles
        self.permission = permission
        self.timer = timer
        self.animationEnabled = animationEnabled
        self.useLocalAssetsIfAvailable = useLocalAssetsIfAvailable
        self.imageTitleSubtitlesDescription = imageTitleSubtitlesDescription
        self.image = image
        self.title = title
        self.subtitle1 = subtitle1
        self.subtitle2 = subtitle2
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case navigationBar
        case footer
        case styles
        case permission
        case timer
        case animationEnabled
        case useLocalAssetsIfAvailable
        case imageTitleSubtitlesDescription
        case image
        case title
        case subtitle1
        case subtitle2
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(navigationBar, forKey: .navigationBar)
        try container.encode(footer, forKey: .footer)
        try container.encode(styles, forKey: .styles)
        try container.encode(permission, forKey: .permission)
        try container.encode(timer, forKey: .timer)
        try container.encode(animationEnabled, forKey: .animationEnabled)
        try container.encode(useLocalAssetsIfAvailable, forKey: .useLocalAssetsIfAvailable)
        try container.encode(imageTitleSubtitlesDescription, forKey: .imageTitleSubtitlesDescription)
        try container.encode(image, forKey: .image)
        try container.encode(title, forKey: .title)
        try container.encode(subtitle1, forKey: .subtitle1)
        try container.encode(subtitle2, forKey: .subtitle2)
    }
}

