//
// ScreenBasicPaywallAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Screen basic paywall */
public struct ScreenBasicPaywallAllOf: Codable, JSONEncodable, Hashable {

    public var screenBasicPaywall: String
    public var navigationBar: PaywallNavigationBar?
    public var footer: PaywallFooter?
    public var title: Text
    public var subtitle: Text
    public var divider: Divider?
    public var media: Media?
    public var list: RegularList
    public var loader: Loader?
    /** Purchase flags */
    public var flags: [PurchaseFlag]
    public var subscriptions: SubscriptionList
    public var currencyFormat: CurrencyFormatKind
    public var styles: ScreenBasicPaywallBlock

    public init(screenBasicPaywall: String, navigationBar: PaywallNavigationBar? = nil, footer: PaywallFooter? = nil, title: Text, subtitle: Text, divider: Divider? = nil, media: Media? = nil, list: RegularList, loader: Loader? = nil, flags: [PurchaseFlag], subscriptions: SubscriptionList, currencyFormat: CurrencyFormatKind, styles: ScreenBasicPaywallBlock) {
        self.screenBasicPaywall = screenBasicPaywall
        self.navigationBar = navigationBar
        self.footer = footer
        self.title = title
        self.subtitle = subtitle
        self.divider = divider
        self.media = media
        self.list = list
        self.loader = loader
        self.flags = flags
        self.subscriptions = subscriptions
        self.currencyFormat = currencyFormat
        self.styles = styles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case screenBasicPaywall
        case navigationBar
        case footer
        case title
        case subtitle
        case divider
        case media
        case list
        case loader
        case flags
        case subscriptions
        case currencyFormat
        case styles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(screenBasicPaywall, forKey: .screenBasicPaywall)
        try container.encodeIfPresent(navigationBar, forKey: .navigationBar)
        try container.encodeIfPresent(footer, forKey: .footer)
        try container.encode(title, forKey: .title)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encodeIfPresent(divider, forKey: .divider)
        try container.encodeIfPresent(media, forKey: .media)
        try container.encode(list, forKey: .list)
        try container.encodeIfPresent(loader, forKey: .loader)
        try container.encode(flags, forKey: .flags)
        try container.encode(subscriptions, forKey: .subscriptions)
        try container.encode(currencyFormat, forKey: .currencyFormat)
        try container.encode(styles, forKey: .styles)
    }
}

