//
// ScreenProgressBarTitleAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Screen - Progress bar/Title */
public struct ScreenProgressBarTitleAllOf: Codable, JSONEncodable, Hashable {

    public var progressBarTitleDescription: String
    public var progressBar: ProgressBar
    public var title: Text
    public var subtitle: Text?

    public init(progressBarTitleDescription: String, progressBar: ProgressBar, title: Text, subtitle: Text? = nil) {
        self.progressBarTitleDescription = progressBarTitleDescription
        self.progressBar = progressBar
        self.title = title
        self.subtitle = subtitle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case progressBarTitleDescription
        case progressBar
        case title
        case subtitle
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(progressBarTitleDescription, forKey: .progressBarTitleDescription)
        try container.encode(progressBar, forKey: .progressBar)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(subtitle, forKey: .subtitle)
    }
}

