//
// ScreenInputType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Possible data types for input on screen */
public enum ScreenInputType: String, Codable, CaseIterable {
    case string = "string"
    case int = "int"
    case double = "double"
    case date = "date"
    case liststring = "listString"
    case listint = "listInt"
    case listdouble = "listDouble"
    case listdate = "listDate"
}
