//
// ScreenTransitionKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Screen transition kind */
public enum ScreenTransitionKind: String, Codable, CaseIterable {
    case _default = "Default"
    case modal = "Modal"
}
