//
// ScreenBasicPaywallBlockAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Styles for ScreenBasicPaywall */
public struct ScreenBasicPaywallBlockAllOf: Codable, JSONEncodable, Hashable {

    public var bodyColor: String?
    public var bodyOpacity: String?
    public var bodyShadowMask: RgbaShadowMask?

    public init(bodyColor: String? = nil, bodyOpacity: String? = nil, bodyShadowMask: RgbaShadowMask? = nil) {
        self.bodyColor = bodyColor
        self.bodyOpacity = bodyOpacity
        self.bodyShadowMask = bodyShadowMask
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bodyColor
        case bodyOpacity
        case bodyShadowMask
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bodyColor, forKey: .bodyColor)
        try container.encodeIfPresent(bodyOpacity, forKey: .bodyOpacity)
        try container.encodeIfPresent(bodyShadowMask, forKey: .bodyShadowMask)
    }
}

