//
// ScreenSliderAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Screen - slider */
public struct ScreenSliderAllOf: Codable, JSONEncodable, Hashable {

    public var sliderDescription: String
    public var slider: Slider

    public init(sliderDescription: String, slider: Slider) {
        self.sliderDescription = sliderDescription
        self.slider = slider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sliderDescription
        case slider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sliderDescription, forKey: .sliderDescription)
        try container.encode(slider, forKey: .slider)
    }
}

