//
// ScreenImageTitleSubtitleMultipleSelectionListAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Screen - Image/Title/Subtitle/Multiple selection list */
public struct ScreenImageTitleSubtitleMultipleSelectionListAllOf: Codable, JSONEncodable, Hashable {

    public var imageTitleSubtitleMultipleSelectionListDescription: String
    public var image: Image
    /** Defines the scale of the image in percentage */
    public var imageScale: Double?
    public var title: Text
    public var subtitle: Text
    public var list: MultipleSelectionList

    public init(imageTitleSubtitleMultipleSelectionListDescription: String, image: Image, imageScale: Double? = nil, title: Text, subtitle: Text, list: MultipleSelectionList) {
        self.imageTitleSubtitleMultipleSelectionListDescription = imageTitleSubtitleMultipleSelectionListDescription
        self.image = image
        self.imageScale = imageScale
        self.title = title
        self.subtitle = subtitle
        self.list = list
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imageTitleSubtitleMultipleSelectionListDescription
        case image
        case imageScale
        case title
        case subtitle
        case list
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(imageTitleSubtitleMultipleSelectionListDescription, forKey: .imageTitleSubtitleMultipleSelectionListDescription)
        try container.encode(image, forKey: .image)
        try container.encodeIfPresent(imageScale, forKey: .imageScale)
        try container.encode(title, forKey: .title)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encode(list, forKey: .list)
    }
}

