//
// ScreenType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The screen type */
public enum ScreenType: String, Codable, CaseIterable {
    case customScreen = "CustomScreen"
    case screenImageTitleSubtitles = "ScreenImageTitleSubtitles"
    case screenSlider = "ScreenSlider"
    case screenTableMultipleSelection = "ScreenTableMultipleSelection"
    case screenTableSingleSelection = "ScreenTableSingleSelection"
    case screenTitleSubtitleField = "ScreenTitleSubtitleField"
    case screenProgressBarTitle = "ScreenProgressBarTitle"
    case screenTwoColumnMultipleSelection = "ScreenTwoColumnMultipleSelection"
    case screenTwoColumnSingleSelection = "ScreenTwoColumnSingleSelection"
    case screenImageTitleSubtitleList = "ScreenImageTitleSubtitleList"
    case screenTitleSubtitleCalendar = "ScreenTitleSubtitleCalendar"
    case screenTitleSubtitlePicker = "ScreenTitleSubtitlePicker"
    case screenImageTitleSubtitlePicker = "ScreenImageTitleSubtitlePicker"
    case screenImageTitleSubtitleMultipleSelectionList = "ScreenImageTitleSubtitleMultipleSelectionList"
    case screenTooltipPermissions = "ScreenTooltipPermissions"
}
