//
// ScreenPermissionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Screen permission type */
public enum ScreenPermissionType: String, Codable, CaseIterable {
    case notifications = "notifications"
    case ads = "ads"
}
