//
// ScreenTitleSubtitleCalendarAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Screen - Title/Subtitle/Calendar */
public struct ScreenTitleSubtitleCalendarAllOf: Codable, JSONEncodable, Hashable {

    public var titleSubtitleCalendarDescription: String
    public var title: Text
    public var subtitle: Text
    public var calendar: Calendar

    public init(titleSubtitleCalendarDescription: String, title: Text, subtitle: Text, calendar: Calendar) {
        self.titleSubtitleCalendarDescription = titleSubtitleCalendarDescription
        self.title = title
        self.subtitle = subtitle
        self.calendar = calendar
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case titleSubtitleCalendarDescription
        case title
        case subtitle
        case calendar
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(titleSubtitleCalendarDescription, forKey: .titleSubtitleCalendarDescription)
        try container.encode(title, forKey: .title)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encode(calendar, forKey: .calendar)
    }
}

