//
// ScreenTitleSubtitlePickerAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Screen - Title/Subtitle/Picker */
public struct ScreenTitleSubtitlePickerAllOf: Codable, JSONEncodable, Hashable {

    public var titleSubtitlePickerDescription: String
    public var title: Text
    public var subtitle: Text
    public var picker: Picker

    public init(titleSubtitlePickerDescription: String, title: Text, subtitle: Text, picker: Picker) {
        self.titleSubtitlePickerDescription = titleSubtitlePickerDescription
        self.title = title
        self.subtitle = subtitle
        self.picker = picker
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case titleSubtitlePickerDescription
        case title
        case subtitle
        case picker
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(titleSubtitlePickerDescription, forKey: .titleSubtitlePickerDescription)
        try container.encode(title, forKey: .title)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encode(picker, forKey: .picker)
    }
}

