//
// SelectionListItemBlockElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Possible elements on selection list */
public enum SelectionListItemBlockElement: String, Codable, CaseIterable {
    case image = "Image"
    case title = "Title"
    case subtitle = "Subtitle"
    case checkBox = "CheckBox"
}
