//
// SingleSelectionListItemType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Combination of fields for single selection list item */
public enum SingleSelectionListItemType: String, Codable, CaseIterable {
    case imageTitleSubtitle = "ImageTitleSubtitle"
    case titleSubtitleImage = "TitleSubtitleImage"
    case titleSubtitle = "TitleSubtitle"
    case titleImage = "TitleImage"
    case imageTitle = "ImageTitle"
    case title = "Title"
}
