//
// SlideContent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Slide content */
public struct SlideContent: Codable, JSONEncodable, Hashable {

    public var image: Image
    public var title: Text
    public var subtitle1: Text
    public var subtitle2: Text

    public init(image: Image, title: Text, subtitle1: Text, subtitle2: Text) {
        self.image = image
        self.title = title
        self.subtitle1 = subtitle1
        self.subtitle2 = subtitle2
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
        case title
        case subtitle1
        case subtitle2
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(image, forKey: .image)
        try container.encode(title, forKey: .title)
        try container.encode(subtitle1, forKey: .subtitle1)
        try container.encode(subtitle2, forKey: .subtitle2)
    }
}

