//
// SliderItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Information about one slide of slider */
public struct SliderItem: Codable, JSONEncodable, Hashable {

    /** Section display start */
    public var valueFrom: Int
    /** Section display end */
    public var valueTo: Int
    public var content: SlideContent

    public init(valueFrom: Int, valueTo: Int, content: SlideContent) {
        self.valueFrom = valueFrom
        self.valueTo = valueTo
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case valueFrom
        case valueTo
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(valueFrom, forKey: .valueFrom)
        try container.encode(valueTo, forKey: .valueTo)
        try container.encode(content, forKey: .content)
    }
}

