//
// Slider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Slider */
public struct Slider: Codable, JSONEncodable, Hashable {

    public var kind: SliderKind
    public var timer: ElementTimer
    /** Sections for slider */
    public var items: [SliderItem]
    public var styles: SliderBlock
    public var box: Box

    public init(kind: SliderKind, timer: ElementTimer, items: [SliderItem], styles: SliderBlock, box: Box) {
        self.kind = kind
        self.timer = timer
        self.items = items
        self.styles = styles
        self.box = box
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case timer
        case items
        case styles
        case box
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(timer, forKey: .timer)
        try container.encode(items, forKey: .items)
        try container.encode(styles, forKey: .styles)
        try container.encode(box, forKey: .box)
    }
}

