//
// SliderKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Slider kind */
public enum SliderKind: String, Codable, CaseIterable {
    case image = "Image"
    case imageTitle = "ImageTitle"
    case imageTitleSubtitle1 = "ImageTitleSubtitle1"
    case imageTitleSubtitle1Subtitle2 = "ImageTitleSubtitle1Subtitle2"
}
