//
// SubscriptionListItemType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Combination of fields for subscription list item */
public enum SubscriptionListItemType: String, Codable, CaseIterable {
    case checkboxLabels = "CheckboxLabels"
    case labelsCheckbox = "LabelsCheckbox"
    case subscriptionListItemType1 = "SubscriptionListItemType1"
    case subscriptionListItemType2 = "SubscriptionListItemType2"
    case subscriptionListItemType3 = "SubscriptionListItemType3"
    case subscriptionListItemType4 = "SubscriptionListItemType4"
    case subscriptionListItemType5 = "SubscriptionListItemType5"
}
