//
// SubscriptionViewKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Variants of subscription view */
public enum SubscriptionViewKind: String, Codable, CaseIterable {
    case vertical = "Vertical"
    case horizontal = "Horizontal"
    case subscriptionViewKind1 = "SubscriptionViewKind1"
    case subscriptionViewKind2 = "SubscriptionViewKind2"
    case subscriptionViewKind3 = "SubscriptionViewKind3"
    case subscriptionViewKind4 = "SubscriptionViewKind4"
    case subscriptionViewKind5 = "SubscriptionViewKind5"
}
