//
// SubscriptionListItemType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Combination of fields for subscription list item */
public enum SubscriptionListItemType: String, Codable, CaseIterable {
    case checkboxPeriodPriceDescription = "CheckboxPeriodPriceDescription"
    case checkboxPeriodPrice = "CheckboxPeriodPrice"
    case checkboxPeriod = "CheckboxPeriod"
}
