//
// TemplateParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Template parameters */
public struct TemplateParameters: Codable, JSONEncodable, Hashable {

    /** Dictionary of labels styles */
    public var labels: [String: LabelBlock]
    /** Template link dictionary */
    public var links: [String: String]

    public init(labels: [String: LabelBlock], links: [String: String]) {
        self.labels = labels
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case labels
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(labels, forKey: .labels)
        try container.encode(links, forKey: .links)
    }
}

