//
// TextKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Text kind */
public enum TextKind: String, Codable, CaseIterable {
    case _default = "default"
    case template = "template"
}
