//
// TimerUnit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Timer unit */
public enum TimerUnit: String, Codable, CaseIterable {
    case seconds = "Seconds"
    case milliseconds = "Milliseconds"
}
