//
// TooltipImagePosition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Tooltip image position */
public enum TooltipImagePosition: String, Codable, CaseIterable {
    case top = "top"
    case bottom = "bottom"
    case _left = "left"
    case _right = "right"
}
