//
// Tooltip.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Tooltip parameters */
public struct Tooltip: Codable, JSONEncodable, Hashable {

    public var image: Image
    public var title: Text
    public var position: PositionOnDevice
    public var styles: TooltipBlock
    public var box: Box

    public init(image: Image, title: Text, position: PositionOnDevice, styles: TooltipBlock, box: Box) {
        self.image = image
        self.title = title
        self.position = position
        self.styles = styles
        self.box = box
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
        case title
        case position
        case styles
        case box
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(image, forKey: .image)
        try container.encode(title, forKey: .title)
        try container.encode(position, forKey: .position)
        try container.encode(styles, forKey: .styles)
        try container.encode(box, forKey: .box)
    }
}

