//
// TwoColumnMultipleSelectionListItemType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Combination of fields for two column multiple selection list item */
public enum TwoColumnMultipleSelectionListItemType: String, Codable, CaseIterable {
    case tittle = "Tittle"
    case titleSubtitle = "TitleSubtitle"
    case smallImageTitle = "SmallImageTitle"
    case mediumImageTitle = "MediumImageTitle"
    case fullImage = "FullImage"
    case bigImageTitle = "BigImageTitle"
}
