//
// TwoColumnSingleSelectionListItemType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Combination of fields for two column single selection list item */
public enum TwoColumnSingleSelectionListItemType: String, Codable, CaseIterable {
    case tittle = "Tittle"
    case titleSubtitle = "TitleSubtitle"
    case smallImageTitle = "SmallImageTitle"
    case mediumImageTitle = "MediumImageTitle"
    case fullImage = "FullImage"
    case bigImageTitle = "BigImageTitle"
}
