//
// VerticalAlignment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Vertical alignment */
public enum VerticalAlignment: String, Codable, CaseIterable {
    case top = "top"
    case center = "center"
    case bottom = "bottom"
}
